version: "3.8"
services:
  app:
    container_name: lnmarkets-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      LNM_API_KEY:
      LNM_API_SECRET:
      LNM_PASSPHRASE:
      TAAPI_API_KEY:
    command: ["node", "main.mjs"]
